import { TrainerScenario } from "../types";

export const antiProcrastinationScenario: TrainerScenario = {
  id: "anti-procrastination",
  resultCalculator: "anti-procrastination",
  steps: [
    {
      id: "ap-intro",
      type: "intro",
      title: "Антипрокрастинация. Малый шаг",
      description:
        "Не «сделай проект», а «сделай шаг 15 минут». Этот тренажёр поможет разобрать задачу, которую вы откладываете, декомпозировать её в микро-шаг, запустить таймер и зафиксировать результат.",
    },
    {
      id: "ap-task",
      type: "text-input",
      title: "Какую задачу вы откладываете?",
      description: "Выберите одну конкретную задачу, которая вызывает внутреннее сопротивление.",
      placeholder: "Например: начать писать отчёт, записаться к врачу...",
      scoreCategory: "task",
    },
    {
      id: "ap-category",
      type: "single-choice",
      title: "К какой области относится задача?",
      scoreCategory: "category",
      options: [
        { id: "work", label: "Работа", score: 1 },
        { id: "money", label: "Деньги", score: 1 },
        { id: "sales", label: "Продажи", score: 1 },
        { id: "project", label: "Проект", score: 1 },
        { id: "learning", label: "Обучение", score: 1 },
        { id: "sport", label: "Спорт", score: 1 },
        { id: "household", label: "Быт", score: 1 },
        { id: "personal", label: "Личное", score: 1 },
        { id: "other-cat", label: "Другое", score: 1 },
      ],
    },
    {
      id: "ap-value",
      type: "scale",
      title: "Насколько важна эта задача?",
      description: "Оцените реальную важность для вашей жизни.",
      scaleMin: 1,
      scaleMax: 10,
      scaleLabels: { min: "Не очень важна", max: "Критически важна" },
      scoreCategory: "value",
    },
    {
      id: "ap-complexity",
      type: "scale",
      title: "Насколько она сложна?",
      description: "Оцените субъективную сложность задачи.",
      scaleMin: 1,
      scaleMax: 10,
      scaleLabels: { min: "Элементарная", max: "Очень сложная" },
      scoreCategory: "complexity",
    },
    {
      id: "ap-resistance",
      type: "scale",
      title: "Уровень сопротивления",
      description: "Насколько сильно вы НЕ хотите за неё браться прямо сейчас?",
      scaleMin: 1,
      scaleMax: 10,
      scaleLabels: { min: "Почти нет сопротивления", max: "Максимальное сопротивление" },
      scoreCategory: "resistance",
    },
    {
      id: "ap-reason",
      type: "single-choice",
      title: "Почему вы откладываете?",
      description: "Определить причину — уже половина решения.",
      scoreCategory: "delay_reason",
      options: [
        { id: "fear-fail", label: "Страх неудачи", score: 1 },
        { id: "fear-judge", label: "Страх оценки", score: 1 },
        { id: "no-energy", label: "Нет энергии", score: 1 },
        { id: "no-start", label: "Не знаю с чего начать", score: 1 },
        { id: "too-big", label: "Слишком большая задача", score: 1 },
        { id: "no-plan", label: "Нет чёткого плана", score: 1 },
        { id: "perfectionism", label: "Перфекционизм", score: 1 },
        { id: "boring", label: "Неинтересно", score: 1 },
        { id: "no-deadline", label: "Нет дедлайна", score: 1 },
        { id: "no-belief", label: "Не верю в результат", score: 1 },
        { id: "other-reason", label: "Другое", score: 1 },
      ],
    },
    {
      id: "ap-micro",
      type: "text-input",
      title: "Какой самый маленький шаг можно сделать за 15 минут?",
      description: "Декомпозируйте задачу в один конкретный микро-шаг.",
      placeholder: "Например: открыть документ и написать план из 5 пунктов...",
      hints: [
        "Написать план",
        "Сделать 1 звонок",
        "Открыть документ",
        "Сделать расчёт",
        "Написать 5 строк",
        "Найти 3 источника",
        "Создать структуру",
      ],
      scoreCategory: "micro_step",
    },
    {
      id: "ap-confirm",
      type: "confirm",
      title: "Вы готовы посвятить 15 минут только этому шагу?",
      description: "Только один шаг. Только 15 минут. Ничего больше.",
      confirmYesStep: "ap-timer",
      confirmNoStep: "ap-micro",
    },
    {
      id: "ap-timer",
      type: "timer",
      title: "Время действовать",
      description: "Сосредоточьтесь на своём микро-шаге. Без отвлечений.",
      timerDuration: 15,
      scoreCategory: "timer",
    },
    {
      id: "ap-done",
      type: "single-choice",
      title: "Вы завершили шаг?",
      description: "Будьте честны — любой результат ценен.",
      scoreCategory: "action_result",
      options: [
        { id: "done-full", label: "Да, полностью", score: 3 },
        { id: "done-partial", label: "Частично", score: 2 },
        { id: "done-no", label: "Нет", score: 1 },
      ],
    },
    {
      id: "ap-easier",
      type: "text-input",
      title: "Что оказалось легче, чем вы ожидали?",
      placeholder: "Например: начать было не так страшно, как казалось...",
      scoreCategory: "reflection",
    },
    {
      id: "ap-harder",
      type: "text-input",
      title: "Что оказалось сложнее?",
      placeholder: "Например: сложно было не отвлекаться на телефон...",
      scoreCategory: "reflection",
    },
    {
      id: "ap-resistance-after",
      type: "scale",
      title: "Уровень сопротивления сейчас",
      description: "Как изменилось ваше сопротивление после работы?",
      scaleMin: 1,
      scaleMax: 10,
      scaleLabels: { min: "Сопротивления нет", max: "Всё ещё максимальное" },
      scoreCategory: "resistance_after",
    },
    {
      id: "ap-info",
      type: "info",
      title: "Вы сделали главное — начали",
      description:
        "Каждый запуск тренажёра — это победа над прокрастинацией. Со временем система покажет ваши паттерны: самую частую причину откладывания, динамику сопротивления и рост дисциплины. 3 дня подряд — «Запуск». 7 дней — «Ритм». 21 день — «Новая привычка».",
    },
    {
      id: "ap-result",
      type: "result",
      title: "Ваш результат",
      resultTemplate: "anti-procrastination",
    },
  ],
};
