import { TrainerScenario } from "../types";

export const emotionsScenario: TrainerScenario = {
  id: "emotions-in-action",
  resultCalculator: "emotions-in-action",
  steps: [
    {
      id: "em-intro",
      type: "intro",
      title: "Эмоции в действии",
      description:
        "Эмоция — это сигнал. Сейчас мы разберём её и переведём в действие. Вы научитесь распознавать эмоции, понимать их источник, выбирать экологичную реакцию и видеть повторяющиеся паттерны.",
    },
    {
      id: "em-emotion",
      type: "multiple-choice",
      title: "Что вы чувствуете прямо сейчас?",
      description: "Выберите до 2 эмоций, которые ближе всего к вашему состоянию.",
      scoreCategory: "emotion",
      maxSelect: 2,
      optionGroups: [
        {
          label: "Негативные",
          optionIds: [
            "fear", "anxiety", "panic", "shame", "guilt", "anger",
            "irritation", "resentment", "jealousy", "envy",
            "helplessness", "disappointment", "fatigue", "apathy",
            "loneliness", "insecurity", "tension", "overload",
          ],
        },
        {
          label: "Позитивные",
          optionIds: [
            "joy", "interest", "inspiration", "excitement",
            "calm", "confidence", "gratitude", "pride",
            "anticipation", "enthusiasm",
          ],
        },
      ],
      options: [
        { id: "fear", label: "Страх", score: 1, tags: ["negative", "fear-group"] },
        { id: "anxiety", label: "Тревога", score: 1, tags: ["negative", "fear-group"] },
        { id: "panic", label: "Паника", score: 1, tags: ["negative", "fear-group"] },
        { id: "shame", label: "Стыд", score: 1, tags: ["negative", "guilt-group"] },
        { id: "guilt", label: "Вина", score: 1, tags: ["negative", "guilt-group"] },
        { id: "anger", label: "Злость", score: 1, tags: ["negative", "anger-group"] },
        { id: "irritation", label: "Раздражение", score: 1, tags: ["negative", "anger-group"] },
        { id: "resentment", label: "Обида", score: 1, tags: ["negative", "anger-group"] },
        { id: "jealousy", label: "Ревность", score: 1, tags: ["negative", "anger-group"] },
        { id: "envy", label: "Зависть", score: 1, tags: ["negative", "anger-group"] },
        { id: "helplessness", label: "Беспомощность", score: 1, tags: ["negative", "fatigue-group"] },
        { id: "disappointment", label: "Разочарование", score: 1, tags: ["negative", "fatigue-group"] },
        { id: "fatigue", label: "Усталость", score: 1, tags: ["negative", "fatigue-group"] },
        { id: "apathy", label: "Апатия", score: 1, tags: ["negative", "fatigue-group"] },
        { id: "loneliness", label: "Одиночество", score: 1, tags: ["negative", "fatigue-group"] },
        { id: "insecurity", label: "Неуверенность", score: 1, tags: ["negative", "fear-group"] },
        { id: "tension", label: "Напряжение", score: 1, tags: ["negative", "fear-group"] },
        { id: "overload", label: "Перегруз", score: 1, tags: ["negative", "fatigue-group"] },
        { id: "joy", label: "Радость", score: 1, tags: ["positive"] },
        { id: "interest", label: "Интерес", score: 1, tags: ["positive"] },
        { id: "inspiration", label: "Вдохновение", score: 1, tags: ["positive"] },
        { id: "excitement", label: "Азарт", score: 1, tags: ["positive"] },
        { id: "calm", label: "Спокойствие", score: 1, tags: ["positive"] },
        { id: "confidence", label: "Уверенность", score: 1, tags: ["positive"] },
        { id: "gratitude", label: "Благодарность", score: 1, tags: ["positive"] },
        { id: "pride", label: "Гордость", score: 1, tags: ["positive"] },
        { id: "anticipation", label: "Предвкушение", score: 1, tags: ["positive"] },
        { id: "enthusiasm", label: "Воодушевление", score: 1, tags: ["positive"] },
      ],
    },
    {
      id: "em-intensity",
      type: "scale",
      title: "Насколько интенсивна эта эмоция?",
      description: "Оцените силу того, что вы чувствуете прямо сейчас.",
      scaleMin: 1,
      scaleMax: 10,
      scaleLabels: { min: "Едва заметна", max: "Захлёстывает полностью" },
      scoreCategory: "intensity",
    },
    {
      id: "em-trigger",
      type: "single-choice",
      title: "Что вызвало эту эмоцию?",
      description: "Найдите триггер — что стало причиной?",
      scoreCategory: "trigger",
      options: [
        { id: "work", label: "Работа", score: 1 },
        { id: "money", label: "Деньги", score: 1 },
        { id: "relationships", label: "Отношения", score: 1 },
        { id: "family", label: "Семья", score: 1 },
        { id: "self-esteem", label: "Самооценка", score: 1 },
        { id: "publicity", label: "Публичность", score: 1 },
        { id: "mistake", label: "Ошибка", score: 1 },
        { id: "criticism", label: "Критика", score: 1 },
        { id: "uncertainty", label: "Неопределённость", score: 1 },
        { id: "tiredness", label: "Усталость", score: 1 },
        { id: "conflict", label: "Конфликт", score: 1 },
        { id: "comparison", label: "Сравнение", score: 1 },
        { id: "other-trigger", label: "Другое", score: 1 },
      ],
    },
    {
      id: "em-body",
      type: "multiple-choice",
      title: "Где в теле вы ощущаете эту эмоцию?",
      description: "Эмоции всегда отражаются в теле. Выберите все зоны, которые откликаются.",
      scoreCategory: "body",
      options: [
        { id: "chest", label: "Сжатие в груди", score: 1 },
        { id: "throat", label: "Ком в горле", score: 1 },
        { id: "shoulders", label: "Напряжение в плечах", score: 1 },
        { id: "head", label: "Головная боль", score: 1 },
        { id: "breathing", label: "Учащённое дыхание", score: 1 },
        { id: "heaviness", label: "Тяжесть", score: 1 },
        { id: "weakness", label: "Упадок сил", score: 1 },
        { id: "trembling", label: "Дрожь", score: 1 },
        { id: "emptiness", label: "Пустота", score: 1 },
        { id: "warmth", label: "Тепло", score: 1 },
        { id: "lightness", label: "Лёгкость", score: 1 },
        { id: "relaxation", label: "Расслабление", score: 1 },
      ],
    },
    {
      id: "em-thought",
      type: "single-choice",
      title: "Какая мысль приходит первой?",
      description: "Автоматическая мысль — это то, что всплывает само. Нет плохих ответов.",
      scoreCategory: "thought",
      options: [
        { id: "cant-do", label: "У меня не получится", score: 1, tags: ["negative-thought"] },
        { id: "not-enough", label: "Я недостаточно хорош(а)", score: 1, tags: ["negative-thought"] },
        { id: "judged", label: "Меня осудят", score: 1, tags: ["negative-thought"] },
        { id: "must-cope", label: "Я должен(на) справиться", score: 1, tags: ["negative-thought"] },
        { id: "unfair", label: "Это несправедливо", score: 1, tags: ["negative-thought"] },
        { id: "unlucky", label: "Мне снова не повезло", score: 1, tags: ["negative-thought"] },
        { id: "wont-manage", label: "Я не справлюсь", score: 1, tags: ["negative-thought"] },
        { id: "ruined", label: "Я всё испортил(а)", score: 1, tags: ["negative-thought"] },
        { id: "unappreciated", label: "Меня не ценят", score: 1, tags: ["negative-thought"] },
        { id: "tired-thought", label: "Я устал(а)", score: 1, tags: ["negative-thought"] },
        { id: "can-do", label: "Я справлюсь", score: 1, tags: ["positive-thought"] },
        { id: "chance", label: "Это шанс", score: 1, tags: ["positive-thought"] },
        { id: "try", label: "Я могу попробовать", score: 1, tags: ["positive-thought"] },
        { id: "other-thought", label: "Другое", score: 1, tags: ["neutral-thought"] },
      ],
    },
    {
      id: "em-impulse",
      type: "single-choice",
      title: "Какой импульс возникает первым?",
      description: "Что вы хотите сделать, когда чувствуете эту эмоцию? Не думайте — выбирайте первое, что пришло.",
      scoreCategory: "impulse",
      options: [
        { id: "avoid", label: "Избегаю", score: 1, weight: 8 },
        { id: "postpone", label: "Откладываю", score: 1, weight: 8 },
        { id: "attack", label: "Нападаю", score: 1, weight: 9 },
        { id: "withdraw", label: "Замыкаюсь", score: 1, weight: 7 },
        { id: "justify", label: "Оправдываюсь", score: 1, weight: 6 },
        { id: "devalue", label: "Обесцениваю", score: 1, weight: 7 },
        { id: "comply", label: "Соглашаюсь против себя", score: 1, weight: 7 },
        { id: "overwork", label: "Работать ещё больше", score: 1, weight: 6 },
        { id: "freeze", label: "Ничего не делаю", score: 1, weight: 7 },
        { id: "act", label: "Иду в действие", score: 1, weight: 2 },
        { id: "discuss", label: "Обсуждаю", score: 1, weight: 3 },
        { id: "other-impulse", label: "Другое", score: 1, weight: 5 },
      ],
    },
    {
      id: "em-strategy",
      type: "single-choice",
      title: "Выберите конструктивную стратегию",
      description: "Варианты подобраны на основе вашей эмоции. Выберите то, что кажется наиболее подходящим.",
      scoreCategory: "strategy",
      meta: { dynamic: true },
      options: [],
    },
    {
      id: "em-plan",
      type: "text-input",
      title: "Ваш план действия",
      description: "Опишите конкретный шаг, который вы готовы сделать. Что именно и когда?",
      placeholder: "Например: Сегодня вечером поговорю с партнёром о том, что меня беспокоит...",
      scoreCategory: "action",
    },
    {
      id: "em-info",
      type: "info",
      title: "Вы только что проделали серьёзную работу",
      description:
        "Вы назвали эмоцию, нашли её в теле, определили триггер, заметили автоматическую мысль, осознали импульс и выбрали конструктивную стратегию. Это и есть эмоциональный интеллект в действии. С каждым прохождением ваши паттерны становятся яснее, а реакции — осознаннее.",
    },
    {
      id: "em-result",
      type: "result",
      title: "Ваш результат",
      resultTemplate: "emotions-in-action",
    },
  ],
};
