import { TrainerScenario } from "../types";

export const moneyAnxietyScenario: TrainerScenario = {
  id: "money-anxiety",
  resultCalculator: "money-anxiety",
  steps: [
    {
      id: "ma-intro",
      type: "intro",
      title: "Деньги без тревоги",
      description:
        "Это не про учёт доходов. Это про психологию денег — страхи, установки, импульсы. Сейчас мы разберём вашу денежную ситуацию, найдём триггер, переведём тревогу в конкретное финансовое действие и посчитаем индекс финансовой устойчивости.",
    },
    {
      id: "ma-situation",
      type: "single-choice",
      title: "Какая денежная ситуация вызывает напряжение?",
      description: "Выберите то, что ближе всего к вашему текущему состоянию.",
      scoreCategory: "situation",
      options: [
        { id: "shortage", label: "Нехватка денег", score: 1 },
        { id: "income-growth", label: "Рост дохода", score: 1 },
        { id: "price-raise", label: "Повышение цены", score: 1 },
        { id: "sales", label: "Продажи", score: 1 },
        { id: "debts", label: "Долги", score: 1 },
        { id: "credits", label: "Кредиты", score: 1 },
        { id: "investments", label: "Инвестиции", score: 1 },
        { id: "unstable-income", label: "Нестабильный доход", score: 1 },
        { id: "lost-client", label: "Потеря клиента", score: 1 },
        { id: "big-purchase", label: "Большая покупка", score: 1 },
        { id: "scaling", label: "Масштабирование", score: 1 },
        { id: "other-situation", label: "Другое", score: 1 },
      ],
    },
    {
      id: "ma-trigger",
      type: "single-choice",
      title: "Какой тип денежного триггера?",
      description: "Что именно стоит за напряжением? Выберите основной триггер.",
      scoreCategory: "trigger",
      options: [
        { id: "fear-loss", label: "Страх потери", score: 1 },
        { id: "fear-instability", label: "Страх нестабильности", score: 1 },
        { id: "fear-judgment", label: "Страх осуждения", score: 1 },
        { id: "fear-responsibility", label: "Страх ответственности", score: 1 },
        { id: "fear-success", label: "Страх успеха", score: 1 },
        { id: "comparison", label: "Сравнение с другими", score: 1 },
        { id: "insufficiency", label: "Чувство недостаточности", score: 1 },
        { id: "hypercontrol", label: "Контроль и гиперответственность", score: 1 },
        { id: "avoidance", label: "Избегание денег", score: 1 },
        { id: "guilt-income", label: "Вина за доход", score: 1 },
        { id: "other-trigger", label: "Другое", score: 1 },
      ],
    },
    {
      id: "ma-emotion",
      type: "single-choice",
      title: "Какую эмоцию это вызывает?",
      description: "Что вы чувствуете, когда думаете об этой ситуации?",
      scoreCategory: "emotion",
      options: [
        { id: "m-anxiety", label: "Тревога", score: 1 },
        { id: "m-fear", label: "Страх", score: 1 },
        { id: "m-panic", label: "Паника", score: 1 },
        { id: "m-guilt", label: "Вина", score: 1 },
        { id: "m-shame", label: "Стыд", score: 1 },
        { id: "m-envy", label: "Зависть", score: 1 },
        { id: "m-irritation", label: "Раздражение", score: 1 },
        { id: "m-anger", label: "Злость", score: 1 },
        { id: "m-insecurity", label: "Неуверенность", score: 1 },
        { id: "m-helplessness", label: "Беспомощность", score: 1 },
        { id: "m-excitement", label: "Воодушевление", score: 1 },
        { id: "m-interest", label: "Интерес", score: 1 },
        { id: "m-calm", label: "Спокойствие", score: 1 },
      ],
    },
    {
      id: "ma-intensity",
      type: "scale",
      title: "Насколько сильна денежная тревога?",
      description: "Оцените интенсивность прямо сейчас.",
      scaleMin: 1,
      scaleMax: 10,
      scaleLabels: { min: "Едва заметна", max: "Захлёстывает" },
      scoreCategory: "money_anxiety",
    },
    {
      id: "ma-thought",
      type: "single-choice",
      title: "Какая мысль приходит первой?",
      description: "Автоматическая денежная мысль — то, что всплывает само.",
      scoreCategory: "thought",
      options: [
        { id: "always-short", label: "Денег всегда мало", score: 1, tags: ["scarcity"] },
        { id: "cant-earn", label: "Я не умею зарабатывать", score: 1, tags: ["scarcity"] },
        { id: "wont-pay", label: "Мне не заплатят", score: 1, tags: ["distrust"] },
        { id: "clients-leave", label: "Клиенты уйдут", score: 1, tags: ["distrust"] },
        { id: "not-worth", label: "Я не стою этих денег", score: 1, tags: ["worthlessness"] },
        { id: "work-more", label: "Нужно работать больше", score: 1, tags: ["overwork"] },
        { id: "no-risk", label: "Лучше не рисковать", score: 1, tags: ["money-fear"] },
        { id: "money-hard", label: "Деньги — это сложно", score: 1, tags: ["money-fear"] },
        { id: "wealth-danger", label: "Богатство опасно", score: 1, tags: ["money-fear"] },
        { id: "not-allowed", label: "Мне нельзя больше", score: 1, tags: ["money-guilt"] },
        { id: "ill-manage", label: "Я справлюсь", score: 1, tags: ["positive"] },
        { id: "this-is-growth", label: "Это рост", score: 1, tags: ["positive"] },
        { id: "other-thought", label: "Другое", score: 1, tags: ["neutral"] },
      ],
    },
    {
      id: "ma-impulse",
      type: "single-choice",
      title: "Какой импульс возникает первым?",
      description: "Что вы хотите сделать прямо сейчас? Не думайте — выбирайте первое.",
      scoreCategory: "impulse",
      options: [
        { id: "lower-price", label: "Снизить цену", score: 1, weight: 8 },
        { id: "refuse", label: "Отказаться", score: 1, weight: 9 },
        { id: "postpone", label: "Отложить решение", score: 1, weight: 7 },
        { id: "avoid-talk", label: "Избегать обсуждения денег", score: 1, weight: 8 },
        { id: "work-free", label: "Работать бесплатно", score: 1, weight: 9 },
        { id: "overwork", label: "Перерабатывать", score: 1, weight: 6 },
        { id: "freeze-project", label: "Заморозить проект", score: 1, weight: 8 },
        { id: "do-nothing", label: "Ничего не делать", score: 1, weight: 8 },
        { id: "calculate", label: "Идти в расчёт", score: 1, weight: 2 },
        { id: "raise-price", label: "Поднять цену", score: 1, weight: 3 },
        { id: "discuss-terms", label: "Обсудить условия", score: 1, weight: 3 },
      ],
    },
    {
      id: "ma-rational",
      type: "single-choice",
      title: "Рациональная альтернатива",
      description: "Варианты подобраны на основе вашей денежной мысли. Выберите то, что поможет сместить фокус.",
      scoreCategory: "rational",
      meta: { dynamic: true },
      options: [],
    },
    {
      id: "ma-strategy",
      type: "single-choice",
      title: "Выберите конструктивную стратегию",
      description: "Какое финансовое действие вы готовы предпринять?",
      scoreCategory: "strategy",
      options: [
        { id: "str-calculate", label: "Финансовый расчёт", score: 3 },
        { id: "str-talk-money", label: "Разговор о деньгах", score: 3 },
        { id: "str-raise", label: "Повышение цены", score: 3 },
        { id: "str-delegate", label: "Делегирование", score: 2 },
        { id: "str-budget", label: "Составление бюджета", score: 3 },
        { id: "str-cut", label: "Пересмотр расходов", score: 2 },
        { id: "str-test", label: "Тест нового продукта", score: 3 },
        { id: "str-find-client", label: "Поиск нового клиента", score: 3 },
        { id: "str-learn", label: "Обучение", score: 2 },
        { id: "str-invest", label: "Инвестирование", score: 3 },
        { id: "str-reserve", label: "Создание резерва", score: 3 },
      ],
    },
    {
      id: "ma-step",
      type: "text-input",
      title: "Какой финансовый шаг вы сделаете в течение 48 часов?",
      description: "Конкретное действие. Чем точнее — тем выше вероятность выполнения.",
      placeholder: "Например: посчитаю расходы за месяц, подниму цену на 10%...",
      scoreCategory: "action",
      hints: ["Посчитать расходы", "Поднять цену", "Составить бюджет", "Обсудить оплату", "Создать резерв"],
    },
    {
      id: "ma-done",
      type: "single-choice",
      title: "Насколько вы уверены, что выполните этот шаг?",
      description: "Честная оценка. Осознание уровня готовности — тоже результат.",
      scoreCategory: "commitment",
      options: [
        { id: "done-full", label: "Точно сделаю", score: 3 },
        { id: "done-partial", label: "Скорее да, но не уверен(а)", score: 2 },
        { id: "done-no", label: "Пока не готов(а)", score: 1 },
      ],
    },
    {
      id: "ma-info",
      type: "info",
      title: "Вы только что проделали важную работу",
      description:
        "Вы определили денежный триггер, заметили автоматическую мысль, осознали импульс и выбрали рациональную альтернативу. Каждый раз, когда вы переводите тревогу в действие — ваша финансовая устойчивость растёт. Система отследит вашу динамику.",
    },
    {
      id: "ma-result",
      type: "result",
      title: "Ваш результат",
      resultTemplate: "money-anxiety",
    },
  ],
};
