import { TrainerScenario } from "../types";

export const selfEsteemScenario: TrainerScenario = {
  id: "self-esteem",
  resultCalculator: "self-esteem",
  steps: [
    {
      id: "se-intro",
      type: "intro",
      title: "Самооценка и внутренняя опора",
      description:
        "Самооценка — это не «я хороший», а «я вижу свои действия, выводы и рост». Сейчас мы зафиксируем ваш день через достижения, реакции и рефлексию. 5–7 минут для формирования внутренней опоры.",
    },
    {
      id: "se-achievements",
      type: "multiple-choice",
      title: "Что вы сегодня сделали?",
      description: "Выберите минимум 3 пункта. Не обязательно великие дела — любой шаг считается.",
      scoreCategory: "achievements",
      options: [
        { id: "ach-task", label: "Завершил задачу", score: 1 },
        { id: "ach-talk", label: "Провёл важный разговор", score: 1 },
        { id: "ach-decision", label: "Принял решение", score: 1 },
        { id: "ach-boundary", label: "Отстоял границу", score: 1 },
        { id: "ach-new", label: "Начал что-то новое", score: 1 },
        { id: "ach-rest", label: "Отдохнул осознанно", score: 1 },
        { id: "ach-impulse", label: "Сдержал импульс", score: 1 },
        { id: "ach-support", label: "Поддержал себя", score: 1 },
        { id: "ach-helped", label: "Помог кому-то", score: 1 },
        { id: "ach-learned", label: "Узнал что-то новое", score: 1 },
        { id: "ach-routine", label: "Выполнил рутину без отговорок", score: 1 },
        { id: "ach-honest", label: "Был честен с собой", score: 1 },
      ],
    },
    {
      id: "se-difficulty",
      type: "text-input",
      title: "Что сегодня было непросто?",
      description: "Опишите ситуацию, которая вызвала напряжение или дискомфорт.",
      placeholder: "Например: сложный разговор с коллегой, не хватило сил на задачу...",
      scoreCategory: "difficulty",
    },
    {
      id: "se-coping",
      type: "single-choice",
      title: "Как вы справились?",
      description: "Выберите реакцию, наиболее близкую к вашему поведению.",
      scoreCategory: "coping",
      options: [
        { id: "cop-acted", label: "Действовал", score: 10, weight: 10 },
        { id: "cop-help", label: "Попросил помощи", score: 8, weight: 8 },
        { id: "cop-postpone", label: "Отложил осознанно", score: 7, weight: 7 },
        { id: "cop-boundary", label: "Защитил границы", score: 10, weight: 10 },
        { id: "cop-mistake", label: "Ошибся, но сделал вывод", score: 9, weight: 9 },
        { id: "cop-ignored", label: "Проигнорировал", score: 3, weight: 3 },
        { id: "cop-avoided", label: "Избежал", score: 2, weight: 2 },
      ],
    },
    {
      id: "se-lesson",
      type: "text-input",
      title: "Чему вас научил этот день?",
      description: "Один вывод, одно наблюдение — фиксация делает опыт ценным.",
      placeholder: "Например: я могу справляться даже когда устал...",
      scoreCategory: "lesson",
    },
    {
      id: "se-self-value",
      type: "scale",
      title: "Уровень самоценности сегодня",
      description: "Насколько вы сейчас цените и уважаете себя?",
      scaleMin: 1,
      scaleMax: 10,
      scaleLabels: { min: "Совсем не ценю", max: "Полностью ценю" },
      scoreCategory: "self_value",
    },
    {
      id: "se-external",
      type: "scale",
      title: "Зависимость от чужого мнения",
      description: "Насколько сегодня ваше состояние зависело от того, что думают и говорят другие?",
      scaleMin: 1,
      scaleMax: 10,
      scaleLabels: { min: "Не зависело", max: "Полностью зависело" },
      scoreCategory: "external_dependency",
    },
    {
      id: "se-info",
      type: "info",
      title: "Вы фиксируете свою опору",
      description:
        "Вы только что честно посмотрели на свой день: увидели достижения, признали трудности, отметили реакцию и сделали вывод. Это и есть внутренняя опора — не на эмоции, а на факты. Продолжайте ежедневно: 7 дней — «Формирую опору». 30 дней — «Стабильность». 90 дней — «Внутренняя зрелость».",
    },
    {
      id: "se-result",
      type: "result",
      title: "Ваш результат",
      resultTemplate: "self-esteem",
    },
  ],
};
