ALTER TABLE online_games ADD COLUMN IF NOT EXISTS rematch_offered_by VARCHAR(64) DEFAULT NULL;
ALTER TABLE online_games ADD COLUMN IF NOT EXISTS rematch_status VARCHAR(20) DEFAULT NULL;
ALTER TABLE online_games ADD COLUMN IF NOT EXISTS rematch_game_id INTEGER DEFAULT NULL;